import os
import json
import logging
import boto3
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

logger = logging.getLogger()
logger.setLevel(logging.INFO)

BEDROCK_MODEL = os.environ.get('BEDROCK_MODEL', 'us.anthropic.claude-sonnet-4-6-20251001-v1:0')
SES_FROM = os.environ.get('SES_FROM', 'devops-guru@techstream.io')
SES_TO   = os.environ.get('SES_TO',   'incidents@techstream.io')
ONCALL   = os.environ.get('ONCALL',   'oncall@techstream.io')

SUMMARY_SCHEMA = {
    'root_cause_summary': 'string — one sentence',
    'leading_golden_signal': 'one of: Errors | Latency | Traffic | Saturation',
    'remediation_taken': 'string — what the automated system did',
    'customer_impact': 'string — estimated blast radius',
    'recommended_followup': 'string — next manual steps'
}

bedrock = boto3.client('bedrock-runtime')
ses = boto3.client('ses')


def _invoke_bedrock(insight):
    prompt = (
        'You are a DevOps incident analyst. Analyse the following AWS DevOps Guru insight JSON '
        'and return a JSON object with EXACTLY these keys (no extra keys, no markdown):\n'
        f'{json.dumps(SUMMARY_SCHEMA, indent=2)}\n\n'
        f'Insight:\n{json.dumps(insight, indent=2)}\n\n'
        'Return only the JSON object.'
    )
    body = json.dumps({
        'anthropic_version': 'bedrock-2023-05-31',
        'max_tokens': 1024,
        'messages': [{'role': 'user', 'content': prompt}]
    })
    response = bedrock.invoke_model(
        modelId=BEDROCK_MODEL,
        body=body,
        contentType='application/json',
        accept='application/json'
    )
    response_body = json.loads(response['body'].read())
    content = response_body.get('content', [])
    if not content:
        raise ValueError(f'Bedrock returned empty content (stop_reason={response_body.get("stop_reason")})')
    text = content[0].get('text', '')
    if not text:
        raise ValueError('Bedrock content[0] has no text field')
    return json.loads(text)


def handler(event, context):
    message = event['Records'][0]['Sns']['Message']
    insight = json.loads(message)

    try:
        summary = _invoke_bedrock(insight)
        logger.info('Bedrock RCA generated for insight %s', insight.get('InsightId'))
    except Exception:
        logger.exception('Bedrock invocation failed — using fallback summary')
        summary = {
            'root_cause_summary': 'Could not generate automatic summary — check Lambda logs.',
            'leading_golden_signal': 'Errors',
            'remediation_taken': 'N/A',
            'customer_impact': 'Unknown',
            'recommended_followup': 'Investigate the DevOps Guru insight manually.'
        }

    msg = MIMEMultipart('mixed')
    msg['Subject'] = (
        f"[TechStream RCA] {insight.get('InsightId', 'unknown')} | "
        f"{insight.get('Severity', 'unknown')} | "
        f"{summary.get('leading_golden_signal', 'Errors')} anomaly"
    )
    msg['From'] = SES_FROM
    msg['To'] = SES_TO
    msg['Cc'] = ONCALL

    html = f"""<html><body>
<h2>TechStream Incident RCA — Auto-generated</h2>
<table border="0" cellpadding="6" style="border-collapse:collapse">
  <tr><td><b>Root Cause</b></td><td>{summary.get('root_cause_summary')}</td></tr>
  <tr><td><b>Leading Signal</b></td><td>{summary.get('leading_golden_signal')}</td></tr>
  <tr><td><b>Remediation Taken</b></td><td>{summary.get('remediation_taken')}</td></tr>
  <tr><td><b>Customer Impact</b></td><td>{summary.get('customer_impact')}</td></tr>
  <tr><td><b>Follow-up</b></td><td>{summary.get('recommended_followup')}</td></tr>
</table>
<hr/>
<p style="color:#666;font-size:11px">
  Generated by TechStream self-healing pipeline · Model: {BEDROCK_MODEL}
</p>
</body></html>"""

    msg.attach(MIMEText(html, 'html'))
    attachment = MIMEApplication(json.dumps(insight, indent=2).encode('utf-8'))
    attachment.add_header('Content-Disposition', 'attachment', filename='insight_export.json')
    msg.attach(attachment)

    ses.send_raw_email(
        Source=SES_FROM,
        Destinations=[SES_TO, ONCALL],
        RawMessage={'Data': msg.as_string()}
    )

    return {'statusCode': 200}
