global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'techstream_flask'
    static_configs:
      - targets: ['app:8000']
        labels:
          instance_id: 'local'
          instance_name: 'local-dev'
          availability_zone: 'local'
    metrics_path: /metrics
