apiVersion: 1

datasources:
  - name: AMP
    type: prometheus
    uid: prometheus
    url: ${AMP_ENDPOINT}
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: '15s'
      sigV4Auth: true
      sigV4Region: ${AWS_REGION}
      sigV4AuthType: default

  - name: CloudWatch
    type: cloudwatch
    uid: cloudwatch
    editable: false
    jsonData:
      defaultRegion: ${AWS_REGION}
      authType: default
